export const ACTION="ACTION";

export const LOG_IN = "LOG_IN";
export const LOG_IN_REQUEST = "LOG_IN_REQUEST";
export const LOG_INOUT_QUERY = "LOG_INOUT_QUERY";
export const LOGGED_IN_SUCCESS = "LOGGED_IN_SUCCESS";
export const LOGGED_IN_FAILURE = "LOGGED_IN_FAILURE";

export const LOG_OUT = "LOG_OUT";
export const LOGGED_OUT_SUCCESS = "LOGGED_OUT_SUCCESS";
export const LOGGED_OUT_FAILURE = "LOGGED_OUT_FAILURE";

export const SIGN_OFF = "SIGN_OFF";
export const SIGN_OFF_SUCCESS = "SIGN_OFF_SUCCESS";
export const SIGN_OFF_FAILURE = "SIGN_OFF_FAILURE";

export const NAV_SET_FUNCTION = "NAV_SET_FUNCTION";
export const NAV_CLEAR_FUNCTION = "NAV_CLEAR_FUNCTION";
export const NAV_SET_VISIBLE = "NAV_SET_VISIBLE";

export const TRANSLATION_STORE = "TRANSLATION_STORE";
export const TRANSLATION_CHANGE = "TRANSLATION_CHANGE";
export const TRANSLATION_REQUEST = "TRANSLATION_REQUEST";

export const TODO_STORE = "TODO_STORE";
export const TODO_EXTRACT = "TODO_EXTRACT";
export const TODO_EXTRACT_LOADING = "TODO_EXTRACT_LOADING";
export const TODO_EXTRACT_LOADED = "TODO_EXTRACT_LOADED";
export const TODO_EXTRACT_FAIL = "TODO_EXTRACT_FAIL";
export const TODO_REMOVE = "TODO_REMOVE";

export const QR_REGISTRATION_SAVE = "QR_REGISTRATION_SAVE";
export const QR_REGISTER_SUCCESS = "QR_REGISTER_SUCCESS";
export const QR_REGISTER_FAILED = "QR_REGISTER_FAILED";
export const QR_REGISTRATION_LOAD = "QR_REGISTRATION_LOAD";
export const QR_REGISTRATION_LOADING = "QR_REGISTRATION_LOADING";
